# Generated by Django 2.0.4 on 2018-05-19 20:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180519_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='description2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
