# Generated by Django 2.0.4 on 2018-05-20 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_posts_description2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='description1',
        ),
    ]
