# Generated by Django 2.0.4 on 2018-05-20 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20180520_0105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description1',
            new_name='description',
        ),
    ]
