# Generated by Django 2.0.4 on 2018-05-20 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20180520_0108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description2',
            new_name='description1',
        ),
    ]
