# Generated by Django 2.0.4 on 2018-05-20 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20180520_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='description2',
        ),
    ]
